Bring pre-exec up to current standars

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -7,7 +7,17 @@
 . scripts/common
 
 set -eux # -x for verbose logging to juju debug-log
-[[ -d exec.d ]] && ( for f in exec.d/*/charm-pre-install; do [[ -x $f ]] && $SHELL -c "$f";done )
+if [[ -d exec.d ]]; then
+ shopt -s nullglob
+ for f in exec.d/*/charm-pre-install; do
+ [[ -x "$f" ]] || continue
+ ${SHELL} -c "$f"|| {
+ ## bail out if anyone fails
+ juju-log -l ERROR "$f: returned exit_status=$? "
+ exit 1
+ }
+ done
+fi
 
 . scripts/common
 juju-log "Installing packages via apt-get"
